[package]
name = "pajero"
version = "0.1.0"
authors = ["Geunwoo Kim <posgnu@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
serde_derive = "1.0.71"
serde = "1.0.71"
serde_json = "1.0"
tempdir = "0.3"

[dependencies.pnet]
version = "0.21.0"
features = ["pcap"]